# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqjdIZl1m0iSc0Gh4s6p6G4yqS3HlD7s
"""

a=print("Hello, world!")

print(type(a))

#1. write a program and take the three number and finds the sum of the three number

num1=int(input("Enter the first number :"))
num2=int(input("Enter the second number :"))
num3=int(input("Enter the third number :"))

sum=num1+num2+num3

print("The sum of the three number is=", sum)



#2. write a program for print all prime numbers up to 100 Starts of the prime number will be decide of the users.

start = int(input("Enter starting number: "))

for num in range(start, 101):
    if num > 1:
        is_prime = True

        for i in range(2, num):
            if num % i == 0:
                is_prime = False
                break

        if is_prime:
            print(num)

# Method 2: while loop
print("Using while loop:")
i = 5
while i <= 50:
    print(i)
    i += 5

# write a program and add two number using function
#1. write a program and take the three number and finds the sum of the three number

def add(num1,num2,num3):
    return num1+num2+num3

num1=int(input("Enter the first number :"))
num2=int(input("Enter the second number :"))
num3=int(input("Enter the third number :"))

sum=add(num1,num2,num3)
sum1=add(num1,num2,num3)


print("The sum of the three number is=", sum)
print("The sum of the three number is=", sum1)

def add(a, b):
    return a + b

def operation(func, x, y):
    return func(x, y)

result = operation(add, 10, 20)

print(result)

table = [5 * i for i in range(1, 11)]

for num in table:
    print(num)

import statistics

def process_data(lst):
    # Matrix conversion
    matrix = []
    for i in range(0, len(lst), 3):
        row = lst[i:i+3]
        while len(row) < 3:
            row.append(None)
        matrix.append(row)
    while len(matrix) < 3:
        matrix.append([None, None, None])

    # Tuple and statistics
    tup = tuple(lst)
    mean = statistics.mean(tup)
    median = statistics.median(tup)

    try:
        mode = statistics.mode(tup)
    except:
        mode = "No unique mode"

    # Dictionary output
    result = {
        "Matrix": matrix,
        "Tuple": tup,
        "Mean": mean,
        "Median": median,
        "Mode": mode
    }

    return result


user_list = list(map(int, input("Enter numbers: ").split()))
print(process_data(user_list))

# Write a program using functions to add two numbers. If the sum of these two numbers is greater than the middle value of a user-provided list, print the set of all numbers in the list located between the start and the middle value. If the sum is equal to the middle value, print a dictionary where the key is the index of the middle value and the value is the middle value itself. If the sum is less than the middle value, print a tuple containing all numbers in the list that appear after the middle value.[1, 2]

def add_numbers(a, b):
    return a + b

def process_list(lst, total):
    middle_index = len(lst) // 2
    middle_value = lst[middle_index]

    if total > middle_value:
        result = set(lst[0:middle_index])   # between start and middle
        print("Set:", result)

    elif total == middle_value:
        result = {middle_index: middle_value}
        print("Dictionary:", result)

    else:
        result = tuple(lst[middle_index + 1:])  # after middle value
        print("Tuple:", result)


# Example list
numbers = [1, 2]

# Input two numbers
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

sum_result = add_numbers(num1, num2)

print("Sum:", sum_result)

process_list(numbers, sum_result)

import numpy as np

l = [1, 2, 3, 4, 5]

l1 = l + l
print("l1 =", l1)

l2 = [l], [l]
print("l2 =", l2)

l3 = [[l1] , [l2]]
print("l3 =", l3)





# I want to create a coffee machine of options    based on the options using oops concepts all 5 . clearly define a coffee machine with the options using abstraction , the flow from espresso to americano as a concept of inheritance followed  from them to the other options of the ecofee machine make sure to specify overloading and overriding concepts since the parameters of each recipe of office changes when each of them have different outcomes with same behavioral concept . in python full code


from abc import ABC, abstractmethod


# =========================
# ABSTRACTION
# =========================
class Coffee(ABC):
    def __init__(self, water, coffee_beans, milk=0, sugar=0):
        self._water = water              # Encapsulation
        self._coffee_beans = coffee_beans
        self._milk = milk
        self._sugar = sugar

    @abstractmethod
    def prepare(self):
        pass

    # OVERLOADING (Python style using default arguments)
    def add_extra(self, sugar=0, milk=0):
        self._sugar += sugar
        self._milk += milk
        print(f"Added Sugar: {sugar}, Added Milk: {milk}")


# =========================
# INHERITANCE
# =========================
class Espresso(Coffee):
    def __init__(self):
        super().__init__(water=50, coffee_beans=18)

    def prepare(self):
        print("Preparing Espresso...")
        print(f"Water: {self._water}ml")
        print(f"Coffee Beans: {self._coffee_beans}g")
        print("Espresso Ready!\n")


class Americano(Espresso):   # Americano inherits Espresso
    def __init__(self):
        super().__init__()
        self._water += 100

    # OVERRIDING
    def prepare(self):
        print("Preparing Americano...")
        print(f"Water: {self._water}ml")
        print(f"Coffee Beans: {self._coffee_beans}g")
        print("Americano Ready!\n")


class Latte(Americano):
    def __init__(self):
        super().__init__()
        self._milk = 150

    def prepare(self):
        print("Preparing Latte...")
        print(f"Water: {self._water}ml")
        print(f"Coffee Beans: {self._coffee_beans}g")
        print(f"Milk: {self._milk}ml")
        print("Latte Ready!\n")


class Cappuccino(Latte):
    def __init__(self):
        super().__init__()
        self._milk = 100

    def prepare(self):
        print("Preparing Cappuccino...")
        print(f"Water: {self._water}ml")
        print(f"Coffee Beans: {self._coffee_beans}g")
        print(f"Milk Foam: {self._milk}ml")
        print("Cappuccino Ready!\n")


class Mocha(Latte):
    def __init__(self):
        super().__init__()
        self.chocolate = True

    def prepare(self):
        print("Preparing Mocha...")
        print(f"Water: {self._water}ml")
        print(f"Coffee Beans: {self._coffee_beans}g")
        print(f"Milk: {self._milk}ml")
        print("Chocolate Syrup Added")
        print("Mocha Ready!\n")


# =========================
# COFFEE MACHINE
# =========================
class CoffeeMachine:
    def make_coffee(self, choice):
        menu = {
            1: Espresso(),
            2: Americano(),
            3: Latte(),
            4: Cappuccino(),
            5: Mocha()
        }

        coffee = menu.get(choice)

        if coffee:
            coffee.prepare()
        else:
            print("Invalid Choice")


# =========================
# MAIN PROGRAM
# =========================
machine = CoffeeMachine()

while True:
    print("===== COFFEE MACHINE =====")
    print("1. Espresso")
    print("2. Americano")
    print("3. Latte")
    print("4. Cappuccino")
    print("5. Mocha")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 6:
        print("Thank you for using Coffee Machine!")
        break

    machine.make_coffee(choice)

import numpy as np

# Generate dataset (50 random scores between 0 and 99)
scores = np.random.randint(0, 100, size=50)

print("Student Scores:")
print(scores)

# 1. Basic Statistics
mean_score = np.mean(scores)
median_score = np.median(scores)
highest_score = np.max(scores)
lowest_score = np.min(scores)
std_dev = np.std(scores)

print("\n--- Statistics ---")
print("Mean:", mean_score)
print("Median:", median_score)
print("Highest:", highest_score)
print("Lowest:", lowest_score)
print("Standard Deviation:", std_dev)

# 2. Find Failures (< 40)
fail_students = scores[scores < 40]

# 3. Find Distinction (> 85)
distinction_students = scores[scores > 85]

print("\nFailed Students Scores (<40):")
print(fail_students)

print("\nDistinction Students Scores (>85):")
print(distinction_students)

# 4. Normalize Scores (0 to 1)
normalized_scores = (scores - np.min(scores)) / (np.max(scores) - np.min(scores))

print("\nNormalized Scores:")
print(normalized_scores)

# 5. Reshape into 5 x 10
reshaped_scores = scores.reshape(5, 10)

print("\nReshaped Scores (5 x 10):")
print(reshaped_scores)

# Row-wise averages
row_averages = np.mean(reshaped_scores, axis=1)

print("\nRow-wise Averages:")
print(row_averages)

# 6. Percentiles
p25 = np.percentile(scores, 25)
p50 = np.percentile(scores, 50)
p75 = np.percentile(scores, 75)

print("\nPercentiles:")
print("25th:", p25)
print("50th:", p50)
print("75th:", p75)

# BONUS: Weighted Final Scores
theory = np.random.randint(0, 100, size=50)
practical = np.random.randint(0, 100, size=50)

weighted_scores = (0.4 * theory) + (0.6 * practical)

print("\nTheory Scores:")
print(theory)

print("\nPractical Scores:")
print(practical)

print("\nWeighted Final Scores:")
print(weighted_scores)

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from google.colab import files

# Upload image from your computer
uploaded = files.upload()

# Get uploaded file name
filename = list(uploaded.keys())[0]

# Read image
img = mpimg.imread(filename)

# Normalize if needed
if img.max() > 1.0:
    img = img / 255.0

# Convert to grayscale
gray = np.mean(img[:, :, :3], axis=2)

# Brightness
bright = np.clip(gray + 0.3, 0, 1)
dark = np.clip(gray - 0.3, 0, 1)

# Flip
flip_horizontal = np.fliplr(gray)
flip_vertical = np.flipud(gray)

# Crop
h, w = gray.shape
crop = gray[h//4:h//2, w//4:w//2]

# Display
fig, axes = plt.subplots(2, 3, figsize=(15, 8))

axes[0, 0].imshow(img)
axes[0, 0].set_title("Original")
axes[0, 0].axis("off")

axes[0, 1].imshow(gray, cmap="gray")
axes[0, 1].set_title("Grayscale")
axes[0, 1].axis("off")

axes[0, 2].imshow(bright, cmap="gray")
axes[0, 2].set_title("Bright")
axes[0, 2].axis("off")

axes[1, 0].imshow(dark, cmap="gray")
axes[1, 0].set_title("Dark")
axes[1, 0].axis("off")

axes[1, 1].imshow(flip_horizontal, cmap="gray")
axes[1, 1].set_title("Flip Horizontal")
axes[1, 1].axis("off")

axes[1, 2].imshow(crop, cmap="gray")
axes[1, 2].set_title("Crop")
axes[1, 2].axis("off")

plt.tight_layout()
plt.show()

import pandas as pd

data = {
    'Order ID': ['CA-001', 'CA-002', 'CA-003', 'CA-004', 'CA-005', 'CA-006', 'CA-007', 'CA-008', 'CA-009', 'CA-010'],
    'Region': ['East', 'West', 'South', 'North', 'East', 'West', 'South', 'North', 'East', 'West'],
    'Category': ['Furniture', 'Technology', 'Office Supplies', 'Furniture', 'Technology', 'Office Supplies', 'Furniture', 'Technology', 'Office Supplies', 'Furniture'],
    'Sub-Category': ['Chair', 'Laptop', 'Paper', 'Table', 'Phone', 'Binder', 'Sofa', 'Monitor', 'Pen', 'Bookcase'],
    'Sales': [5000, 12000, 3000, 7000, 9000, 2500, 11000, 15000, 1200, 8000],
    'Profit': [500, 2000, -200, 800, 1500, -100, 1200, 2500, -50, 900],
    'Segment': ['Consumer', 'Corporate', 'Home Office', 'Consumer', 'Corporate', 'Home Office', 'Consumer', 'Corporate', 'Home Office', 'Consumer'],
    'Customer Name': ['Raj', 'Amit', 'Sara', 'John', 'Ali', 'Neha', 'Ravi', 'Karan', 'Pooja', 'Ankit'],
    'Ship Mode': ['Second Class', 'Standard Class', 'First Class', 'Second Class', 'Standard Class', 'First Class', 'Second Class', 'Standard Class', 'First Class', 'Second Class'],
    'State': ['Delhi', 'Mumbai', 'Chennai', 'Jaipur', 'Delhi', 'Mumbai', 'Chennai', 'Jaipur', 'Delhi', 'Mumbai'],
    'Quantity': [2, 3, 10, 4, 5, 8, 2, 3, 15, 1],
    'Discount': [0.1, 0.2, 0.3, 0.1, 0.15, 0.25, 0.05, 0.2, 0.3, 0.1],
    'Order Date': ['2024-01-10', '2024-02-15', '2024-03-20', '2024-04-12', '2024-05-18', '2024-06-22', '2024-07-11', '2024-08-09', '2024-09-14', '2024-10-05']
}

df = pd.DataFrame(data)

print(df.head(10))
print(df.info())
print(df.describe(include='all'))

region_category_summary = df.groupby(['Region', 'Category']).agg({
    'Sales': ['sum', 'mean', 'max'],
    'Profit': ['sum', 'mean', 'max']
})
print(region_category_summary)

subcategory_sales = df.groupby(['Region', 'Sub-Category'])['Sales'].sum().reset_index()

top_3_subcategories = subcategory_sales.groupby('Region').apply(
    lambda x: x.sort_values('Sales', ascending=False).head(3)
)
print(top_3_subcategories)

df['Profit Margin %'] = (df['Profit'] / df['Sales']) * 100
print(df[['Order ID', 'Sales', 'Profit', 'Profit Margin %']])

sales_pivot = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Segment',
    aggfunc='mean'
)
print(sales_pivot)

df['Order Date'] = pd.to_datetime(df['Order Date'])

monthly_profit = df.groupby(df['Order Date'].dt.to_period('M'))['Profit'].sum()
negative_profit_months = monthly_profit[monthly_profit < 0]
print(negative_profit_months)

quarterly_sales_trend = df.set_index('Order Date').resample('Q')['Sales'].sum()
print(quarterly_sales_trend)

highest_sales_region = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
print(highest_sales_region)

highest_profit_category = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
print(highest_profit_category)

top_customers = df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False)
print(top_customers)

shipping_mode_sales = df.groupby('Ship Mode')['Sales'].sum().sort_values(ascending=False)
print(shipping_mode_sales)

state_profit = df.groupby('State')['Profit'].sum().sort_values(ascending=False)
print(state_profit)

loss_states = df.groupby('State')['Profit'].sum().sort_values()
print(loss_states)

segment_profit = df.groupby('Segment')['Profit'].sum()
print(segment_profit)

category_quantity = df.groupby('Category')['Quantity'].sum()
print(category_quantity)

discount_impact = df.groupby('Discount')[['Sales', 'Profit']].mean()
print(discount_impact)